from pathlib import Path

from analysis.h3.causal_prerequisite_provenance import _identity_only_error
from scripts.launch_h1_h2_placement_control import build_control_command


def _build(tmp_path: Path, mode: str):
    bank = tmp_path / "ple.manifest.json" if mode == "mmap" else None
    if bank is not None:
        bank.write_text("{}\n")
    return build_control_command(
        model_directory=tmp_path / "model",
        runtime_directory=tmp_path / "runtime",
        trace_directory=tmp_path / "traces",
        gpu_ids=["0"],
        port=8000,
        cpu_offload_gib=40.0,
        hot_experts=16,
        max_model_len=8192,
        max_num_seqs=1,
        max_num_batched_tokens=2048,
        kv_cache_memory_bytes=1073741824,
        runtime_image="fenix-qwen38:h1-h2-robust-v1",
        expandable_segments=True,
        ple_storage_mode=mode,
        ple_bank_manifest=bank,
    )


def test_resident_control_preserves_h1_h2_prefix_policy(tmp_path: Path):
    env, command = _build(tmp_path, "resident")
    assert env["FENIX_PLE_STORAGE_MODE"] == "resident"
    assert env["FENIX_PREFIX_CACHING"] == "0"
    assert "--no-enable-prefix-caching" in command
    assert "FENIX_PLE_BANK_MANIFEST" not in env


def test_mmap_control_preserves_h1_h2_prefix_policy_and_binds_bank(tmp_path: Path):
    env, command = _build(tmp_path, "mmap")
    assert env["FENIX_PLE_STORAGE_MODE"] == "mmap"
    assert env["FENIX_PREFIX_CACHING"] == "0"
    assert "--no-enable-prefix-caching" in command
    assert env["FENIX_PLE_BANK_MANIFEST"].endswith("/ple.manifest.json")
    assert any("fenix-ple-bank" in token for token in command)


def test_provenance_wrapper_recognizes_only_identity_failures():
    assert _identity_only_error(
        "prerequisite evidence was generated by a different H3 implementation commit"
    )
    assert _identity_only_error(
        "prerequisite placement_invariance: execution-repository identity differs from prerequisite tool_qualification"
    )
    assert not _identity_only_error("tool qualification prerequisite is incomplete")
