"""Causal H3 gate wrapper for analysis-derived semantic prerequisites.

The numerical causal gate remains unchanged. This wrapper only amends the final
prerequisite implementation-provenance check after the base gate has validated
all prerequisite artifact kinds, contract hashes, content predicates, matrix
identity, and campaign fingerprint.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from analysis.h3.causal_gate import causal_campaign_gate
from analysis.h3.common import H3Error, execution_repository_identity, load_json, sha256_file, write_json

IDENTITY_ERROR = "prerequisite evidence was generated by a different H3 implementation commit"


def _resolve_entry(manifest_path: Path, entry: dict[str, Any], label: str) -> tuple[Path, dict[str, Any]]:
    raw = entry.get("artifact")
    expected_sha = entry.get("sha256")
    if not raw or not expected_sha:
        raise H3Error(f"prerequisite {label} is not SHA-bound")
    path = Path(str(raw))
    if not path.is_absolute():
        path = (manifest_path.parent / path).resolve()
    if not path.is_file():
        raise H3Error(f"prerequisite {label} artifact is missing: {path}")
    if sha256_file(path) != str(expected_sha):
        raise H3Error(f"prerequisite {label} SHA drift")
    return path, load_json(path)


def _identity_fp(identity: dict[str, Any]) -> tuple[Any, Any, Any]:
    return (
        identity.get("head"),
        identity.get("tree"),
        identity.get("required_base_commit"),
    )


def _validate_provenance_split(
    prerequisites_path: Path,
    base_gate: dict[str, Any],
    amendment_path: Path,
    contract_path: Path,
) -> dict[str, Any]:
    amendment = load_json(amendment_path)
    if amendment.get("artifact_kind") != "fenix_h3_prerequisite_provenance_amendment":
        raise H3Error("unexpected prerequisite provenance amendment")
    contract_sha = sha256_file(contract_path)
    if amendment.get("base_contract_sha256") != contract_sha:
        raise H3Error("prerequisite provenance amendment is not bound to the H3 contract")

    frozen_identity = base_gate.get("frozen_measurement_execution_repository") or {}
    analysis_identity = base_gate.get("analysis_execution_repository") or {}
    if frozen_identity.get("head") != amendment.get("frozen_measurement_head"):
        raise H3Error("prerequisite provenance amendment uses another frozen measurement HEAD")
    if not frozen_identity or not analysis_identity:
        raise H3Error("causal gate lacks measurement/analysis execution identities")

    frozen_fp = _identity_fp(frozen_identity)
    analysis_fp = _identity_fp(analysis_identity)
    manifest = load_json(prerequisites_path)
    evidence = manifest.get("evidence") or {}
    allowed_analysis = set(str(v) for v in amendment.get("allowed_analysis_derived_prerequisites", []))
    frozen_only = set(str(v) for v in amendment.get("frozen_only_prerequisites", []))
    required = allowed_analysis | frozen_only
    if not required.issubset(set(evidence)):
        raise H3Error(f"prerequisite manifest lacks provenance-amendment entries: {sorted(required - set(evidence))}")

    resolved: dict[str, Any] = {}
    analysis_derived_used: list[str] = []
    for key in sorted(required):
        entry = evidence.get(key)
        if not isinstance(entry, dict):
            raise H3Error(f"prerequisite manifest entry {key} is not an object")
        path, payload = _resolve_entry(prerequisites_path, entry, key)
        identity = execution_repository_identity(payload, f"prerequisite {key}")
        fp = _identity_fp(identity)
        source = None
        if key in frozen_only:
            if fp != frozen_fp:
                raise H3Error(f"frozen-only prerequisite {key} is not generated at frozen e08 identity")
            source = "frozen_measurement_head"
        elif fp == frozen_fp:
            source = "frozen_measurement_head"
        elif fp == analysis_fp:
            source = "analysis_head"
            analysis_derived_used.append(key)
        else:
            raise H3Error(
                f"analysis-derived prerequisite {key} uses unauthorized implementation identity {fp}"
            )

        if key == "placement_invariance" and source == "analysis_head":
            placement_spec = amendment.get("placement_control") or {}
            if payload.get("derived_pass") is not True:
                raise H3Error("analysis-derived placement control did not pass")
            if payload.get("evaluator") != placement_spec.get("evaluator"):
                raise H3Error("analysis-derived placement control uses another evaluator")
            observed_modes = {
                str(row.get("ple_storage_mode"))
                for row in payload.get("placements", [])
                if isinstance(row, dict)
            }
            if observed_modes != set(str(v) for v in placement_spec.get("required_modes", [])):
                raise H3Error("analysis-derived placement control lacks exact resident/mmap modes")
            if payload.get("source_runtime_provenance_invariant") is not True:
                raise H3Error("analysis-derived placement control did not prove source/runtime provenance invariance")

        resolved[key] = {
            "artifact": str(path),
            "sha256": sha256_file(path),
            "artifact_kind": payload.get("artifact_kind"),
            "implementation_identity_source": source,
            "execution_repository": identity,
        }

    return {
        "evidence": resolved,
        "pagecache_control": {
            "passed": True,
            "substitution": "future_aware_causal_belady_upper_bound",
            "gap_promotion_only": True,
        },
        "storage_concurrency": {
            "required_for_conventional_sufficiency": True,
            "applied": False,
        },
        "provenance_amendment_applied": bool(analysis_derived_used),
        "analysis_derived_prerequisites": sorted(analysis_derived_used),
        "amendment_sha256": sha256_file(amendment_path),
    }


def causal_campaign_gate_with_prerequisite_provenance(
    *,
    matrix_path: Path,
    prerequisites_path: Path,
    causality_path: Path,
    contract_path: Path,
    causality_amendment_path: Path,
    promotion_contract_path: Path,
    prerequisite_amendment_path: Path,
    base_out_path: Path,
    out_path: Path,
) -> dict[str, Any]:
    base = causal_campaign_gate(
        matrix_path=matrix_path,
        prerequisites_path=prerequisites_path,
        causality_path=causality_path,
        contract_path=contract_path,
        amendment_path=causality_amendment_path,
        promotion_contract_path=promotion_contract_path,
        out_path=base_out_path,
    )

    if base.get("prerequisite_status") is not None and base.get("prerequisite_error") is None:
        result = dict(base)
        result["prerequisite_provenance_amendment_applied"] = False
        result["prerequisite_provenance_amendment_sha256"] = sha256_file(prerequisite_amendment_path)
        write_json(out_path, result)
        return result

    if base.get("prerequisite_error") != IDENTITY_ERROR:
        raise H3Error(
            "base causal gate failed for a reason other than the explicitly amended prerequisite "
            f"implementation identity: {base.get('prerequisite_error')}"
        )

    status = _validate_provenance_split(
        prerequisites_path=prerequisites_path,
        base_gate=base,
        amendment_path=prerequisite_amendment_path,
        contract_path=contract_path,
    )
    promotion = load_json(promotion_contract_path)
    result = dict(base)
    result["prerequisite_status"] = status
    result["prerequisite_error"] = None
    result["prerequisite_provenance_amendment_applied"] = True
    result["prerequisite_provenance_amendment_sha256"] = sha256_file(prerequisite_amendment_path)

    supported = result.get("preliminary_memory_service_verdict") == "H3_MEMORY_GAP_SUPPORTED"
    result["paper_promotion_verdict"] = (
        str(promotion["promotion"]["supported_verdict"])
        if supported
        else str(promotion["promotion"]["blocked_verdict"])
    )
    result["proceed_to_h4"] = bool(
        supported and promotion["promotion"].get("proceed_to_h4_on_supported_gap")
    )
    write_json(out_path, result)
    return result
